#pragma once

#define REMOTE_SENSORS_TEST 0

#define CONFIG_SENSOR_GENERATE_SERIAL_EVENTS 1



#define COMM_SERIAL Serial1
#define COMM_SERIAL_EVENT serialEvent1


#define CONFIG_LOGGER 1

#define DEBUG_3_ENABLE
#define DEBUG_SERIAL Serial
#define DEBUG_SERIAL_EVENT serialEvent

#define CONFIG_WORKER_PROCESS 1
#define CONFIG_NODE_SCAN_TASK 1

#define CONFIG_NETWORK 1
#define CONFIG_HTTP_SERVER 1
#define CONFIG_HTTP_SERVLET_OUTCONTROL_JS 1
#define CONFIG_SENSOR_STATE_SERVLET 1
#define CONFIG_OUTPUT_CONTROL_SERVLET 1
#define CONFIG_TELNET_SERVER 1
#define CONFIG_TELNET_COMMANDS_SENSORS 1


#define CONFIG_SENSORS_JSON_OUTPUT 1

#define CONFIG_SENSOR_HUB 1
#define CONFIG_SENSOR_HUB_GENERATE_EVENTS 0
//!!
#define CONFIG_SENSOR_GENERATE_EVENTS 1

#define CONFIG_OUTPUT_PROCESS 1
#define CONFIG_OUTPUT_STATE_SENSOR 1
#define CONFIG_DS1820_SENSOR 1
#define CONFIG_SIMPLE_DIGITAL_INPUT_SENSOR 1


#define NUM_OF_OUTPUTS 3

#define OUT_PIN_TEST1 38
#define OUT_PIN_TEST2 38
#define OUT_PIN_TEST3 38

#define OUT_ID_TEST1 0
#define OUT_ID_TEST2 1
#define OUT_ID_TEST3 2
