#pragma once

// c header for the application
#define OUT_ID_HEAT_PUMP_HEATING 0
#define OUT_ID_COOLING 1
#define OUT_ID_HI_HEAING 2
#define OUT_ID_RESERVED 3
#define OUT_ID_AIR_SPEED_2 4
#define OUT_ID_AIR_SPEED_3 5
#define OUT_ID_AIR_POWER_OFF 6
#define OUT_ID_AUX_WATER_HEATER 7
#define OUT_ID_HOT_AIR 8
#define OUT_ID_FLOOR_PUMP 9
#define OUT_ID_WATER_CIRCULATION_PUMP 10
#define OUT_ID_READIATORS_PUMP 11
#define OUT_ID_FLOOR_TEMP_LOWER 12
#define OUT_ID_RADIATOR_TEMP_LOWER 13
#define OUT_ID_FLOOR_TEMP_HIGHER 14
#define OUT_ID_RADIATOR_TEMP_HIGHER 15
