#pragma once

#define COMM_SERIAL Serial1
#define COMM_SERIAL_EVENT serialEvent1


#define CONFIG_LOGGER 1

#define DEBUG_3_ENABLE
#define DEBUG_SERIAL Serial
#define DEBUG_SERIAL_EVENT serialEvent

#define CONFIG_WORKER_PROCESS 1
#define CONFIG_NODE_SCAN_TASK 1

#define CONFIG_NETWORK 1
#define CONFIG_HTTP_SERVER 1
#define CONFIG_HTTP_SERVLET_OUTCONTROL_JS 1
#define CONFIG_SENSOR_STATE_SERVLET 1
#define CONFIG_OUTPUT_CONTROL_SERVLET 1
#define CONFIG_TELNET_SERVER 1
#define CONFIG_TELNET_COMMANDS_SENSORS 1

#define CONFIG_SENSORS_JSON_OUTPUT 1

#define CONFIG_SENSOR_HUB 1
#define CONFIG_SENSOR_HUB_GENERATE_EVENTS 0
//!!
#define CONFIG_SENSOR_GENERATE_EVENTS 1

#define CONFIG_IMPULSE_SENSOR 1
#define CONFIG_PT100_ANALOG_SENSOR 1
#define CONFIG_DS1820_SENSOR 1
#define CONFIG_SIMPLE_DIGITAL_INPUT_SENSOR 1


#define CONFIG_HEATING_CIRCLE_CONTROL_SERVLET 1
#define CONFIG_HEATING_CIRCLE_CONTROL 1
#define CONFIG_HEATING_CIRCLE_CONTROL_STATUS_SENSOR 1

// stop the pumps if heating water supply temp drops below target_temp + PUMP_DISABLE_THOLD_SHIFT
#define PUMP_DISABLE_THOLD_SHIFT -4

// never stop pumps if heating water supply temp is higher than PUMP_DISABLE_MAX_TEMP
#define PUMP_DISABLE_MAX_TEMP 36

// restart pump if heating storage temp raise higer than target_temp + PUMP_ENABLE_THOLD_SHIFT
#define PUMP_ENABLE_THOLD_SHIFT 0

// always restart pumps if heating water supply temp is higher than PUMP_ENABLE_PUMPS_FORCE
#define PUMP_FORCE_ENABLE_TEMP 36

// physical output defs
#define CONFIG_OUTPUT_PROCESS 1
#define CONFIG_OUTPUT_STATE_SENSOR 1

#define NUM_OF_OUTPUTS 16

#define OUT_PIN_HEAT_PUMP_HEATING 26
#define OUT_PIN_COOLING 27
#define OUT_PIN_HI_HEAING 28
#define OUT_PIN_RESERVED 29
#define OUT_PIN_AIR_SPEED_2 30
#define OUT_PIN_AIR_SPEED_3 31
#define OUT_PIN_AIR_POWER_OFF 32
#define OUT_PIN_AUX_WATER_HEATER 33
#define OUT_PIN_HOT_AIR 34
#define OUT_PIN_FLOOR_PUMP 35
#define OUT_PIN_WATER_CIRCULATION_PUMP 36
#define OUT_PIN_READIATORS_PUMP 37
#define OUT_PIN_FLOOR_TEMP_LOWER 38
#define OUT_PIN_RADIATOR_TEMP_LOWER 39
#define OUT_PIN_FLOOR_TEMP_HIGHER 40
#define OUT_PIN_RADIATOR_TEMP_HIGHER 41

#define OUT_ID_HEAT_PUMP_HEATING 0
#define OUT_ID_COOLING 1
#define OUT_ID_HI_HEAING 2
#define OUT_ID_RESERVED 3
#define OUT_ID_AIR_SPEED_2 4
#define OUT_ID_AIR_SPEED_3 5
#define OUT_ID_AIR_POWER_OFF 6
#define OUT_ID_AUX_WATER_HEATER 7
#define OUT_ID_HOT_AIR 8
#define OUT_ID_FLOOR_PUMP 9
#define OUT_ID_WATER_CIRCULATION_PUMP 10
#define OUT_ID_READIATORS_PUMP 11
#define OUT_ID_FLOOR_TEMP_LOWER 12
#define OUT_ID_RADIATOR_TEMP_LOWER 13
#define OUT_ID_FLOOR_TEMP_HIGHER 14
#define OUT_ID_RADIATOR_TEMP_HIGHER 15

