manifest:
  defaults:
    remote: szkudlik-homeAutomation

  remotes:
    - name: szkudlik-homeAutomation
      url-base: https://github.com/szkudlik-homeAutomation

  projects:
    - name: Common_code
      path: src/Common_code
      repo-path: Common_code.git
      import: 
        path-prefix: HeatingControl
        name-allowlist: 
           - TCP_Communication_lib
           - ds1820
      revision: ac15d61bcece7da7ab65d502c8591cc5e636eddd

    - name: ArduinoProcessScheduler    
      path: HeatingControl/src/lib/external/ArduinoProcessScheduler
      repo-path: ArduinoProcessScheduler.git
      revision: 1bb8b676bd4c31d5f43c45ff326cb6af98559c33

  self:
      path: HeatingControl