manifest:
  defaults:
    remote: szkudlik-homeAutomation

  remotes:
    - name: szkudlik-homeAutomation
      url-base: https://github.com/szkudlik-homeAutomation

  projects:
    - name: Common_code
      path: src/Common_code
      repo-path: Common_code.git
      import: 
        path-prefix: HeatingControl
      revision: 77beeff5dfe3d306dd3f8e3401888e65178dbfbd

  self:
      path: HeatingControl