#pragma once

// maximum number of nodes, should not be mode than 32 because of bitmaps
#define MAX_NUM_OF_NODES 32

#define CONFIG_NUM_OF_RETRANSMISSIONS 1

#define CONFIG_MAX_NUM_OF_RETRANSMISSIONS 5

#define CONFIG_TRANSMISSION_SPEED 115200

#define CONFIG_MAX_TRANSMIT_DELAY 100
#define CONFIG_OUTPUT_QUEUE_SIZE 3

#define CONFIG_COMMUNICATION_PAYLOAD_DATA_SIZE 20

