#ifndef OUTPUT_PINS
#define  OUTPUT_PINS

#define NUM_OF_OUTPUTS 3 
//16

#define OUT_PIN_FLOOR_HEAT_VALVE_OPEN 38
#define OUT_PIN_FLOOR_HEAT_VALVE_CLOSE 36
#define OUT_PIN_FLOOR_HEAT_PUMP 40

#define OUT_ID_FLOOR_HEAT_VALVE_OPEN 0
#define OUT_ID_FLOOR_HEAT_VALVE_CLOSE 1
#define OUT_ID_FLOOR_HEAT_PUMP 2

#endif