#pragma once

#define NUM_OF_OUTPUTS 16

#define OUT_PIN_HEAT_PUMP_HEATING 26
#define OUT_PIN_COOLING 27
#define OUT_PIN_HI_HEAING 28
#define OUT_PIN_RESERVED 29
#define OUT_PIN_AIR_SPEED_2 30
#define OUT_PIN_AIR_SPEED_3 31
#define OUT_PIN_AIR_POWER_OFF 32
#define OUT_PIN_AUX_WATER_HEATER 33
#define OUT_PIN_HOT_AIR 34
#define OUT_PIN_FLOOR_PUMP 35
#define OUT_PIN_WATER_CIRCULATION_PUMP 36
#define OUT_PIN_READIATORS_PUMP 37
#define OUT_PIN_FLOOR_TEMP_LOWER 38
#define OUT_PIN_RADIATOR_TEMP_LOWER 39
#define OUT_PIN_FLOOR_TEMP_HIGHER 40
#define OUT_PIN_RADIATOR_TEMP_HIGHER 41

#define OUT_ID_HEAT_PUMP_HEATING 0
#define OUT_ID_COOLING 1
#define OUT_ID_HI_HEAING 2
#define OUT_ID_RESERVED 3
#define OUT_ID_AIR_SPEED_2 4
#define OUT_ID_AIR_SPEED_3 5
#define OUT_ID_AIR_POWER_OFF 6
#define OUT_ID_AUX_WATER_HEATER 7
#define OUT_ID_HOT_AIR 8
#define OUT_ID_FLOOR_PUMP 9
#define OUT_ID_WATER_CIRCULATION_PUMP 10
#define OUT_ID_READIATORS_PUMP 11
#define OUT_ID_FLOOR_TEMP_LOWER 12
#define OUT_ID_RADIATOR_TEMP_LOWER 13
#define OUT_ID_FLOOR_TEMP_HIGHER 14
#define OUT_ID_RADIATOR_TEMP_HIGHER 15

